#!/usr/bin/env python3
"""Unit tests for validate_documentation.py Phase 1 v1.0 kickoff."""

import json
import pytest
from pathlib import Path
import tempfile
import sys
import os
from typing import Dict, Any

# Add parent directory to path so we can import validate_documentation directly
scripts_dir = Path(__file__).parent
sys.path.insert(0, str(scripts_dir))

import validate_documentation as validator_module


class TestValidatorCore:
    """Test core validator engine."""

    def test_smoke_empty_document(self):
        """Empty document should produce error for missing required sections."""
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            doc_path = root / "test.md"
            doc_path.write_text("")

            result = validator_module._validate_single_file(
                doc_path, root, {}, "pilot"
            )
            assert result.valid is False
            assert result.error_count() > 0
            assert result.completeness_score == 0.0

    def test_module_doc_all_sections_present(self):
        """Module doc with all required sections should pass."""
        content = "<!-- akr-generated -->\n# TestModule\n\n## Overview\nThis is a test module.\n\n## Module Files\n- File1.py\n- File2.py\n\n## Operations Map\n| Operation | File | Desc |\n|-----------|------|------|\n| foo() | File1.py | Does foo |\n\n## Architecture Overview\nSimple architecture.\n\n## Business Rules\n| Rule | Owner |\n|------|-------|\n| R1 | team |\n\nGenerated by AKR\n"
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            doc_path = root / "test.md"
            doc_path.write_text(content, encoding='utf-8')

            # Create minimal modules.yaml to trigger module classification
            modules_yaml = root / "modules.yaml"
            modules_yaml.write_text("""
project:
  name: TestProj
  layer: API
  standards_version: v1.0.0
  minimum_standards_version: v1.0.0
  compliance_mode: pilot

modules:
  - name: TestModule
    businessCapability: TestCap
    feature: FN00001_US001
    project_type: api-backend
    status: draft
    max_files: 2
    files:
      - src/file1.py
      - src/file2.py
    doc_output: docs/test.md

database_objects: []
unassigned: []
""", encoding='utf-8')

            index = {
                "test.md": {
                    "doc_type": "module",
                    "module_name": "TestModule",
                    "project_type": "api-backend",
                    "ssg_pass3_source_reread": False,
                    "ssg_pass4_source_reread": False,
                }
            }

            result = validator_module._validate_single_file(
                doc_path, root, index, "pilot"
            )
            assert result.valid is True
            assert result.error_count() == 0
            assert result.completeness_score > 70.0

    def test_module_doc_missing_operations_map(self):
        """Module doc missing Operations Map should fail."""
        content = "<!-- akr-generated -->\n# TestModule\n\n## Overview\nTest.\n\n## Module Files\nTest.\n\n## Architecture Overview\nTest.\n\n## Business Rules\nTest.\n\nGenerated\n"
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            doc_path = root / "test.md"
            doc_path.write_text(content, encoding='utf-8')

            index = {
                "test.md": {
                    "doc_type": "module",
                    "module_name": "TestModule",
                    "project_type": "api-backend",
                    "ssg_pass3_source_reread": False,
                    "ssg_pass4_source_reread": False,
                }
            }

            result = validator_module._validate_single_file(
                doc_path, root, index, "pilot"
            )
            assert result.valid is False
            assert result.error_count() >= 1
            errors_missing_section = [
                i for i in result.issues
                if i.rule == "required-sections" and "Operations Map" in i.message
            ]
            assert len(errors_missing_section) > 0

    def test_module_doc_unresolved_question_marks_production_fails(self):
        """Module doc without question marks should still validate."""
        content = "<!-- akr-generated -->\n# TestModule\n\n## Overview\nContent here.\n\n## Module Files\n- File1.py\n\n## Operations Map\n| Op | File |\n|----|------|\n| x | File1.py |\n\n## Architecture Overview\nArch.\n\n## Business Rules\n| Rule | Owner |\n|------|-------|\n| R1 | team |\n"
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            doc_path = root / "test.md"
            doc_path.write_text(content, encoding='utf-8')

            index = {
                "test.md": {
                    "doc_type": "module",
                    "module_name": "TestModule",
                    "project_type": "api-backend",
                    "ssg_pass3_source_reread": False,
                    "ssg_pass4_source_reread": False,
                }
            }

            result = validator_module._validate_single_file(
                doc_path, root, index, "production"
            )
            # No question mark markers present, should be valid
            assert result.valid is True

    def test_db_object_doc_missing_relationships(self):
        """DB object doc missing Relationships section should fail."""
        content = """# TestTable

## Overview
A test table.

## Schema
Column1: int, Column2: string
"""
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            doc_path = root / "test.md"
            doc_path.write_text(content)

            index = {
                "test.md": {
                    "doc_type": "database_object",
                    "module_name": "TestTable",
                    "object_type": "table",
                }
            }

            result = validator_module._validate_single_file(
                doc_path, root, index, "pilot"
            )
            assert result.valid is False
            assert result.error_count() >= 1
            errors_missing = [
                i for i in result.issues
                if i.rule == "required-sections" and "Relationships" in i.message
            ]
            assert len(errors_missing) > 0

    def test_modules_yaml_exceeds_max_files(self):
        """modules.yaml with module exceeding max_files should fail validation."""
        yaml_content = """
project:
  name: TestProj
  layer: API
  standards_version: v1.0.0
  minimum_standards_version: v1.0.0
  compliance_mode: pilot

modules:
  - name: TestModule
    businessCapability: TestCap
    feature: FN00001_US001
    project_type: api-backend
    status: draft
    max_files: 2
    files:
      - src/file1.py
      - src/file2.py
      - src/file3.py
    doc_output: docs/test.md

database_objects: []
unassigned: []
"""
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            manifest_path = root / "modules.yaml"
            manifest_path.write_text(yaml_content)

            import yaml

            manifest = yaml.safe_load(yaml_content)
            issues = validator_module._validate_manifest_schema(manifest)

            error_msgs = [i.message for i in issues if i.severity == "error"]
            assert any("max_files" in msg for msg in error_msgs)

    def test_modules_yaml_unknown_project_type(self):
        """modules.yaml with unknown project_type should fail validation."""
        yaml_content = """
project:
  name: TestProj
  layer: API
  standards_version: v1.0.0
  minimum_standards_version: v1.0.0
  compliance_mode: pilot

modules:
  - name: TestModule
    businessCapability: TestCap
    feature: FN00001_US001
    project_type: unknown-type
    status: draft
    max_files: 2
    files:
      - src/file1.py
    doc_output: docs/test.md

database_objects: []
unassigned: []
"""
        import yaml

        manifest = yaml.safe_load(yaml_content)
        issues = validator_module._validate_manifest_schema(manifest)

        error_msgs = [i.message for i in issues if i.severity == "error"]
        assert any("project_type" in msg for msg in error_msgs)

    def test_modules_yaml_absent(self):
        """Project without modules.yaml should warn, not fail hard."""
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            doc_path = root / "test.md"
            doc_path.write_text("# Test\n\n## Overview\nTest.", encoding='utf-8')

            # Don't create modules.yaml, so fallback is triggered
            result = validator_module._validate_single_file(
                doc_path, root, {}, "pilot"
            )
            # Should still be valid despite missing modules.yaml
            assert result.valid is True


class TestJSONOutputContract:
    """Test JSON output contract matches Phase 1 spec."""

    def test_json_output_has_required_fields(self):
        """JSON output must include all required summary and result fields."""
        content = "# Test\n\n## Overview\nTest content.\n"
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            doc_path = root / "test.md"
            doc_path.write_text(content, encoding='utf-8')

            result = validator_module._validate_single_file(
                doc_path, root, {}, "pilot"
            )

            result_dict = result.to_dict()
            assert "file_path" in result_dict
            assert "doc_type" in result_dict
            assert "module_name" in result_dict
            assert "completeness_score" in result_dict
            assert "error_count" in result_dict
            assert "warning_count" in result_dict
            assert "issues" in result_dict


class TestTransparencyMarkers:
    """Test transparency marker handling."""

    def test_ai_marker_informational_only(self):
        """Module with minimal content should be valid."""
        content = "# Test\n\n## Overview\nGenerated content here.\n"
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            doc_path = root / "test.md"
            doc_path.write_text(content, encoding='utf-8')

            result = validator_module._validate_single_file(
                doc_path, root, {}, "pilot"
            )

            # No transparency markers present is fine for generic docs
            assert result.valid is True

    def test_deferred_marker_warning(self):
        """DEFERRED marker should produce warning, not error."""
        content = "# Test\n\n## Overview\nDEFERRED: This section will be filled later.\nSome other content.\n"
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            doc_path = root / "test.md"
            doc_path.write_text(content, encoding='utf-8')

            result = validator_module._validate_single_file(
                doc_path, root, {}, "pilot"
            )

            deferred_issues = [
                i for i in result.issues
                if "DEFERRED" in i.message
            ]
            assert any(i.severity == "warning" for i in deferred_issues)


class TestCommandLineInterface:
    """Test CLI argument parsing and validation modes."""

    def test_fail_on_flag_errors(self):
        """--fail-on errors should exit 1 if errors exist."""
        parser = validator_module._build_parser()
        args = parser.parse_args(
            ["--file", "test.md", "--fail-on", "errors", "--output", "json"]
        )
        assert args.fail_on == "errors"

    def test_fail_on_flag_never(self):
        """--fail-on never should always exit 0."""
        parser = validator_module._build_parser()
        args = parser.parse_args(
            ["--file", "test.md", "--fail-on", "never", "--output", "json"]
        )
        assert args.fail_on == "never"

    def test_changed_files_parsing(self):
        """--changed-files should parse environment correctly."""
        import os

        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            test_md = root / "docs" / "test.md"
            test_md.parent.mkdir(parents=True)
            test_md.write_text("# Test\n\n## Overview\nContent.", encoding='utf-8')

            # Simulate GitHub Actions output format
            os.environ["CHANGED_FILES"] = "docs/test.md"

            parsed = validator_module._read_changed_files_from_env()
            assert len(parsed) > 0
            assert any("test.md" in p for p in parsed)


class TestScoringExtensions:
    """Tests for semantic scoring PoC functions."""

    def test_is_template_placeholder_bare_marker(self):
        assert validator_module._is_template_placeholder("❓") is True

    def test_is_template_placeholder_empty(self):
        assert validator_module._is_template_placeholder("") is True
        assert validator_module._is_template_placeholder("   ") is True

    def test_is_template_placeholder_bracket_unchanged(self):
        assert validator_module._is_template_placeholder("[MODULE_NAME]") is True
        assert validator_module._is_template_placeholder("[to be filled]") is True

    def test_is_template_placeholder_real_content(self):
        assert validator_module._is_template_placeholder(
            "Validates course enrollment eligibility before allowing registration"
        ) is False

    def test_read_semantic_score_present(self):
        content = "---\nbusinessCapability: Test\nsemantic-score: 78\n---\n# Doc\n"
        result = validator_module._read_semantic_score_from_front_matter(content)
        assert result == 78.0

    def test_read_semantic_score_absent(self):
        content = "---\nbusinessCapability: Test\n---\n# Doc\n"
        result = validator_module._read_semantic_score_from_front_matter(content)
        assert result is None

    def test_read_semantic_score_malformed(self):
        content = "---\nbusinessCapability: Test\nsemantic-score: notanumber\n---\n"
        result = validator_module._read_semantic_score_from_front_matter(content)
        assert result is None

    def test_compute_combined_score_both_present(self):
        result = validator_module._compute_combined_score(80.0, 70.0)
        assert result == 74.0  # (80*0.4) + (70*0.6) = 32+42

    def test_compute_combined_score_structural_only(self):
        result = validator_module._compute_combined_score(80.0, None)
        assert result == 80.0

    def test_validation_result_includes_combined_score(self):
        """ValidationResult with semantic score sets combined_score field."""
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            doc_path = root / "test.md"
            doc_path.write_text(
                "---\nbusinesscapability: Test\nfeature: FN001\nlayer: API\n"
                "project_type: api-backend\nstatus: draft\ncompliance_mode: pilot\n"
                "semantic-score: 70\n---\n"
                "<!-- akr-generated -->\n## Overview\n## Module Files\n"
                "## Operations Map\n## Architecture Overview\n## Business Rules\n",
                encoding="utf-8",
            )
            result = validator_module._validate_single_file(doc_path, root, {}, "pilot")
            assert result.semantic_score == 70.0
            assert result.combined_score is not None

    def test_validation_result_no_semantic_score_falls_back(self):
        """ValidationResult without semantic score falls back to structural-only combined."""
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            doc_path = root / "test.md"
            doc_path.write_text("## Overview\n", encoding="utf-8")
            result = validator_module._validate_single_file(doc_path, root, {}, "pilot")
            assert result.semantic_score is None
            assert result.combined_score == result.completeness_score


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
